import crypto from 'node:crypto';
import {
  extractBgColor,
  extractDimension,
  extractTheme,
  extractImageType,
  extractPaper,
  isFit,
  isLandscape,
} from '#@/helpers/utils.js';

/**
 * Builds a cache key suffix from query parameters based on asset type.
 * Extracts relevant parameters (bgColor, dimensions, theme, image type, PDF options)
 * and joins them into a comma-separated string.
 *
 * Note: SVG type has no type-specific query parameters (empty branch).
 *
 * @param {import('#@/types.js').AssetType} assetType - The type of asset ('img', 'svg', or 'pdf')
 * @param {{bgColor: string | undefined, width: string | undefined, height: string | undefined, scale: string | undefined, theme: string | undefined, type: string | undefined, paper: string | undefined, landscape: string | undefined, fit: string | undefined}} query - The query parameters from the request
 * @param {{maxWidth: number | undefined, maxHeight: number | undefined}} [options] - Optional constraints for dimension extraction
 * @returns {string} A comma-separated string of key=value pairs for cache key generation
 */
export const getQueryKey = (assetType, query, options) => {
  const queryKey = [];
  const bgColor = extractBgColor(query);
  const dimension = extractDimension(query, options);
  const theme = extractTheme(query);

  if (bgColor) queryKey.push(`bgColor=${bgColor}`);

  if (dimension) {
    queryKey.push(`width=${dimension.width}`);
    queryKey.push(`height=${dimension.height}`);
  }

  if (theme) queryKey.push(`theme=${theme}`);

  if (assetType === 'img') {
    const type = extractImageType(query);
    if (type) queryKey.push(`type=${type}`);
  } else if (assetType === 'svg') {
  } else if (assetType === 'pdf') {
    const paper = extractPaper(query);
    const landscape = isLandscape(query);
    const fit = isFit(query);

    if (paper) queryKey.push(`paper=${paper}`);
    if (landscape) queryKey.push(`landscape=${landscape}`);
    if (fit) queryKey.push(`fit=${fit}`);
  }

  return queryKey.join(',');
};

/**
 * Creates a SHA256 cache key from asset type, encoded code, and query parameters.
 * The key is generated by hashing the concatenation of assetType, encodedCode, and queryKey.
 *
 * @param {{assetType: import('#@/types.js').AssetType | undefined, encodedCode: string | undefined, query: Object | undefined, options: Object | undefined}} params - The parameters object
 * @returns {Buffer|string} SHA256 hash as a Buffer, or empty string if assetType or encodedCode is missing
 */
export default ({
  assetType = 'img',
  encodedCode = '',
  query,
  options,
} = {}) => {
  if (!assetType || !encodedCode) return '';

  let rawData = `${assetType} | ${encodedCode}`;
  const queryKey = getQueryKey(assetType, query, options);

  if (queryKey) {
    rawData = `${rawData} | ${queryKey}`;
  }

  return crypto.createHash('sha256').update(rawData).digest();
};
